# Generated by Django 2.1.1 on 2020-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact_indicator_archive',
            options={'managed': True, 'ordering': ('indicator__name', 'location__name'), 'verbose_name': 'Archive', 'verbose_name_plural': 'Repository Archive'},
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='end_period',
            field=models.IntegerField(default=2020, help_text='This marks the end of reporting. The value must be current year or greater than the start year', verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='start_period',
            field=models.IntegerField(default=2020, help_text='This Year marks the start of the reporting period. NB: 1990 is the Lowest Limit!', verbose_name='Start Year'),
        ),
    ]
