# Generated by Django 2.1.2 on 2020-09-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20200930_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicator',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgPeriodType', verbose_name='Frequency/Periodicity'),
        ),
    ]
