# Generated by Django 2.1.2 on 2020-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20200930_1013'),
        ('home', '0002_stgperiodtype'),
        ('indicators', '0004_auto_20200930_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgindicatordomain',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Indicator Domain', 'verbose_name_plural': 'Indicator Domains'},
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='end_period',
            field=models.IntegerField(default=2020, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='start_period',
            field=models.IntegerField(default=2020, help_text='This Year marks the start of the reporting period. NB: 1990 is             the Lowest Limit!', verbose_name='Start Year'),
        ),
        migrations.AlterUniqueTogether(
            name='factdataindicator',
            unique_together={('indicator', 'location', 'categoryoption', 'datasource', 'start_period', 'end_period')},
        ),
    ]
