# Generated by Django 2.1.2 on 2020-09-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20200930_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact_indicator_archive',
            options={'managed': False, 'ordering': ('indicator__name', 'location__name'), 'verbose_name': 'Archive', 'verbose_name_plural': 'Facts Archive'},
        ),
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('indicator__name', 'location__name'), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Data', 'verbose_name_plural': '  Columnar Form'},
        ),
        migrations.AlterModelOptions(
            name='indicatorproxy',
            options={'managed': True, 'verbose_name': 'Tabular Form', 'verbose_name_plural': '   Tabular Forms'},
        ),
        migrations.AlterModelOptions(
            name='stgindicator',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Indicator', 'verbose_name_plural': '  Indicators'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatorgroup',
            options={'managed': True, 'verbose_name': 'Indicator Group', 'verbose_name_plural': 'Indicator Groups'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatorsupergroup',
            options={'managed': True, 'verbose_name': 'Indicator Groupset', 'verbose_name_plural': 'Indicator Groupsets'},
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stganalyticsnarrative',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicator',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicatordomain',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicatorgroup',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicatornarrative',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicatorreference',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgindicatorsupergroup',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgnarrative_type',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
    ]
