# Generated by Django 2.1.2 on 2020-10-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20200930_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='categoryoption',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='home.StgDisagoptionCombination', verbose_name='Disaggregation Option'),
        ),
    ]
