# Generated by Django 2.1.2 on 2020-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20201008_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicator',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
