# Generated by Django 2.1.2 on 2020-10-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20201009_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicatornarrative',
            name='type',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type'),
        ),
    ]
