# Generated by Django 2.1.2 on 2020-10-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20201009_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicatorgroup',
            name='indicator',
            field=models.ManyToManyField(blank=True, db_table='link_indicator_group', to='indicators.StgIndicator'),
        ),
    ]
