# Generated by Django 2.1.2 on 2020-10-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20201013_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='end_period',
            field=models.IntegerField(default=2020, help_text='This marks the end of reporting. The value must be current         year or greater than the start year', verbose_name='Ending Year'),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='period',
            field=models.CharField(blank=True, max_length=25, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='start_period',
            field=models.IntegerField(default=2020, help_text='This Year marks the start of the reporting period.         NB: 1990 is the Lowest Limit!', verbose_name='Start Year'),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True, verbose_name='Approval Status'),
        ),
    ]
