# Generated by Django 2.1.1 on 2019-11-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facthealthcommodities',
            options={'managed': True, 'ordering': ('product__name', 'location__name'), 'verbose_name': 'Commodities Order', 'verbose_name_plural': 'Commodity Orders'},
        ),
        migrations.AlterModelOptions(
            name='stghealthcommodity',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Commodity', 'verbose_name_plural': ' Health Commodities'},
        ),
    ]
