# Generated by Django 2.1.1 on 2019-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_auto_20191113_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facthealthcommodities',
            name='public_access',
            field=models.CharField(blank=True, default='true', max_length=6, null=True),
        ),
    ]
