# Generated by Django 2.1.1 on 2019-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_auto_20191118_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facthealthcommodities',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Issued'),
        ),
    ]
