# Generated by Django 2.1.1 on 2019-11-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20191008_0740'),
        ('commodities', '0005_auto_20191119_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facthealthcommodities',
            unique_together={('product', 'location')},
        ),
    ]
