# Generated by Django 2.1.1 on 2019-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0005_auto_20191119_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facthealthcommodities',
            name='issue_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date Issued'),
        ),
    ]
