# Generated by Django 2.1.1 on 2019-11-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0008_auto_20191119_1758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facthealthcommodities',
            unique_together=set(),
        ),
    ]
