# Generated by Django 2.1.2 on 2020-09-30 07:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgPeriodType',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Modified')),
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(default='Not Applicable', max_length=50, verbose_name='Value Type')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodicity',
                'verbose_name_plural': 'Period Types',
                'db_table': 'stg_time_period',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
