# Generated by Django 2.1.2 on 2020-09-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stgperiodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategorycombination',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgdatasource',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgdisagoptioncombination',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgdisagregationcategory',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgdisagregationoptions',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgmeasuremethod',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgperiodtype',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgperiodtype',
            name='name',
            field=models.CharField(default='Not Applicable', max_length=50, verbose_name='Period Name'),
        ),
        migrations.AlterField(
            model_name='stgvaluedatatype',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
    ]
