# Generated by Django 2.1.2 on 2020-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200930_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdisagregationoptions',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
