# Generated by Django 2.1.2 on 2020-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201008_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdisagregationoptions',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
