# Generated by Django 2.1.2 on 2020-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201008_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdisagregationcategory',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
