# Generated by Django 2.1.2 on 2020-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201008_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategorycombination',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
