# Generated by Django 2.1.2 on 2020-10-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201008_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdisagoptioncombination',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
