# Generated by Django 2.1.2 on 2020-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201008_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategorycombination',
            name='name',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='stgdisagoptioncombination',
            name='name',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='stgdisagregationcategory',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
