# Generated by Django 2.1.2 on 2020-10-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201008_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgmeasuremethod',
            name='shortname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stgmeasuremethod',
            name='measure_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Measure Type'),
        ),
    ]
