---

- name: find binaries with suid/sgid set
  shell: find / -xdev \( -perm -4000 -o -perm -2000 \) -type f ! -path '/proc/*' -print 2>/dev/null
  register: sbit_binaries
  become: yes
  changed_when: False

- name: remove suid/sgid bit from all binaries except in system
  file: path='{{item}}' mode='a-s' state=file follow=yes
  become: yes
  with_items:
    - '{{ sbit_binaries.stdout_lines | difference(os_security_suid_sgid_system_whitelist)  }}'
