# Generated by Django 2.1.1 on 2019-10-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_indicator_archive',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, verbose_name='Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('start_period', models.IntegerField(default=2019, help_text='This Year marks the start of the reporting period. NB: 1990 is the Lowest Limit!', verbose_name='Start Year')),
                ('end_period', models.IntegerField(default=2019, help_text='This marks the end of reporting. The value must be current year or greater than the start year', verbose_name='Ending Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True, verbose_name='Approval Status')),
                ('comment', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Data Archive',
                'db_table': 'khro_indicator_archive',
                'ordering': ('indicator__name', 'location__name'),
                'managed': False,
            },
        ),
    ]
