# Generated by Django 2.1.1 on 2019-10-05 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20191005_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='stganalyticsnarrative',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID'),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID'),
        ),
        migrations.AddField(
            model_name='stgnarrative_type',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID'),
        ),
    ]
