# Generated by Django 2.1.1 on 2019-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20191005_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Value'),
        ),
    ]
