# Generated by Django 2.1.1 on 2019-10-10 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20191008_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgIndicatorSuperGroup',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('groupset_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('shortname', models.CharField(max_length=120, unique=True, verbose_name='Short Name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Group Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('source_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='External Source')),
                ('public_access', models.CharField(choices=[('false', 'False'), ('true', 'True')], default='True', max_length=6, verbose_name='Publicly Accessible?')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Sort Order')),
                ('indicator_groups', models.ManyToManyField(blank=True, db_table='link_indicator_supergroup', to='indicators.StgIndicatorGroup', verbose_name='Indicator Groups')),
            ],
            options={
                'verbose_name': 'Super Group',
                'verbose_name_plural': ' Super Groups',
                'db_table': 'stg_indicator_supergroup',
                'managed': True,
            },
        ),
    ]
