# Generated by Django 2.1.1 on 2019-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20191010_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, verbose_name='Value'),
        ),
    ]
