# Generated by Django 2.1.1 on 2019-10-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20191015_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicator',
            name='periodicity',
            field=models.CharField(blank=True, default=999, max_length=200, null=True, verbose_name='Measurement Frequency'),
        ),
    ]
