# Generated by Django 2.1.1 on 2019-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20191015_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Value'),
        ),
    ]
