# Generated by Django 2.1.1 on 2019-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20191015_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('indicator__name', 'location__name'), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Data', 'verbose_name_plural': '   Data Form'},
        ),
        migrations.AlterField(
            model_name='stgindicator',
            name='afrocode',
            field=models.CharField(blank=True, max_length=10, verbose_name='KHIS ID'),
        ),
    ]
