# Generated by Django 2.1.1 on 2019-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20191126_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicator',
            name='periodicity',
            field=models.IntegerField(blank=True, default=999, null=True, verbose_name='Frequency'),
        ),
    ]
