---

- name: Add Rabbit APT keys
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present
  become: yes
  tags: ["rabbitmq"]

- name: Add Rabbit APT repos
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
  become: yes
  tags: ["rabbitmq"]

- name: Install rabbitmq
  apt: name=rabbitmq-server state=present update_cache=yes
  become: yes
  tags: ["rabbitmq"]

- name: Activate rabbitmq service
  service: name=rabbitmq-server state=started enabled=yes
  become: yes
  tags: ["rabbitmq"]

- name: Add management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  become: yes
  tags: ["rabbitmq"]
