# Generated by Django 2.1.2 on 2020-09-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgepipeline',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Publications', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='stgknowledgepipelinetype',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchproposal',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchthemes',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Research Theme', 'verbose_name_plural': 'Research Themes'},
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.StgKnowledgePipelineType', verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='co_authors',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='Co-authors'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='erc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.StgEthicsCommittee', verbose_name='Approving Agent'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.StgResearchThemes', verbose_name='Thematic Area'),
        ),
    ]
