# Generated by Django 2.1.2 on 2020-09-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20200930_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgethicscommittee',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Ethics Agent', 'verbose_name_plural': 'Ethics Agents'},
        ),
        migrations.AddField(
            model_name='stgknowledgepipelinetype',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stgdiseasedomain',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipelinetype',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgresearchthemes',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stgresearchtopic',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
    ]
