# Generated by Django 2.1.2 on 2020-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20200930_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='internal_link',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='media/files', verbose_name='File Link'),
        ),
    ]
