# Generated by Django 2.1.2 on 2020-10-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20200930_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgdiseasedomain',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Domain', 'verbose_name_plural': ' ICD-11 Domains'},
        ),
        migrations.AlterModelOptions(
            name='stgknowledgepipeline',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Publications', 'verbose_name_plural': '  Publications'},
        ),
        migrations.AlterModelOptions(
            name='stgknowledgepipelinetype',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Publication Type', 'verbose_name_plural': 'Publication Types'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchproposal',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Proposal', 'verbose_name_plural': ' Proposals'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchthemes',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Thematic Area', 'verbose_name_plural': 'Thematic Areas'},
        ),
    ]
