# Generated by Django 2.1.2 on 2020-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20201008_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgresearchtopic',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
