# Generated by Django 2.1.2 on 2020-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20201008_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stgresearchthemes',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
