# Generated by Django 2.1.2 on 2020-10-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20201008_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgdiseasedomain',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Disease Domain', 'verbose_name_plural': ' Disease Domains'},
        ),
        migrations.AlterModelOptions(
            name='stgethicscommittee',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Ethics Committee', 'verbose_name_plural': 'Ethics Committees'},
        ),
        migrations.AlterModelOptions(
            name='stgknowledgepipeline',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Knowledge Poduct', 'verbose_name_plural': '  Knowledge Poducts'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchproposal',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Research Proposal', 'verbose_name_plural': ' Proposals'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchthemes',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Theme', 'verbose_name_plural': 'Research Themes'},
        ),
        migrations.AlterField(
            model_name='stgdiseasedomain',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='stgdiseasedomain',
            name='name',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='authorization',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='approving authority'),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stgethicscommittee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='co_authors',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='Co-authors'),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='quality_level',
            field=models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Quality level'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='erc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.StgEthicsCommittee', verbose_name='Approving Ethics Body'),
        ),
        migrations.AlterField(
            model_name='stgresearchthemes',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
