# Generated by Django 2.1.2 on 2020-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20201013_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgethicscommittee',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Ethics Committee', 'verbose_name_plural': 'Ethics Body'},
        ),
        migrations.AlterModelOptions(
            name='stgknowledgepipelinetype',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterField(
            model_name='stgdiseasedomain',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='stgknowledgepipeline',
            name='quality_level',
            field=models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=1, verbose_name='Quality level'),
        ),
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='affiliate_insititutions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
