# Generated by Django 2.1.2 on 2020-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20201013_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgresearchtopic',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
