# Generated by Django 2.1.2 on 2020-10-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20201013_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgresearchproposal',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='research.StgResearchTopic', verbose_name='Research Topic'),
            preserve_default=False,
        ),
    ]
