# Generated by Django 2.1.1 on 2019-10-02 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StgCategoryCombination',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categorycombo_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('shortname', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('public_access', models.CharField(max_length=6)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Category Combinations',
                'verbose_name_plural': 'Category Combinations',
                'db_table': 'stg_category_combination',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgDatasource',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('datasource_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=230, verbose_name='Data Source')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('source_type', models.CharField(choices=[('NA', 'Not Specified'), ('routine', 'Routine'), ('survey', 'Survey ')], default='NA', max_length=50, null=True, verbose_name='Source Type')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'stg_datasource',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgDisagoptionCombination',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('disag_optionscombo_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('shortname', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('public_access', models.CharField(max_length=6)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Disaggregation Combination',
                'verbose_name_plural': 'Disaggregation Combinations',
                'db_table': 'stg_disagoption_combination',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgDisagregationCategory',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dimension_type', models.CharField(blank=True, max_length=15, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('datadimension', models.CharField(max_length=6)),
                ('public_access', models.CharField(max_length=6)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Category',
                'verbose_name_plural': 'Disaggregation Categories',
                'db_table': 'stg_disagregation_category',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgDisagregationOptions',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categoryoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('public_access', models.CharField(max_length=6)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Option',
                'verbose_name_plural': 'Disaggregation Options',
                'db_table': 'stg_disagregation_options',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgMeasuremethod',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('measuremethod_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=230, verbose_name='Unit of Measure')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('measure_value', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Factor')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Indicator Measure',
                'verbose_name_plural': 'Indicator Measures',
                'db_table': 'stg_measuremethod',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgValueDatatype',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('valuetype_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=50, verbose_name='Value Type')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Type',
                'verbose_name_plural': 'Data Types',
                'db_table': 'stg_value_datatype',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stgdisagregationcategory',
            name='category_options',
            field=models.ManyToManyField(blank=True, db_table='link_category_disaggregate_options', to='home.StgDisagregationOptions', verbose_name='Disaggregation Options'),
        ),
        migrations.AddField(
            model_name='stgdisagoptioncombination',
            name='category_options',
            field=models.ManyToManyField(blank=True, db_table='link_disagoptioncombo_disagoptions', to='home.StgDisagregationOptions', verbose_name='Disaggregation Combinations'),
        ),
        migrations.AddField(
            model_name='stgcategorycombination',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='link_categorycombo_categories', to='home.StgDisagregationCategory', verbose_name='Category Combinations'),
        ),
    ]
