# Generated by Django 2.1.1 on 2019-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191002_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdisagregationcategory',
            name='name',
            field=models.CharField(default='Not Applicable', max_length=230),
            preserve_default=False,
        ),
    ]
