# Generated by Django 2.1.1 on 2019-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191002_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategorycombination',
            name='name',
            field=models.CharField(default='Not Applicable', max_length=230),
        ),
        migrations.AlterField(
            model_name='stgdisagoptioncombination',
            name='name',
            field=models.CharField(default='Not Applicable', max_length=230),
        ),
    ]
