# Generated by Django 2.1.1 on 2019-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191002_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgdatasource',
            name='sort_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
