# Generated by Django 2.1.1 on 2019-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stglocation',
            name='sort_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
