# Generated by Django 2.1.1 on 2019-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_stglocation_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgeconomiczones',
            name='uuid',
            field=models.CharField(default=1234, max_length=36, verbose_name='Universal Key'),
            preserve_default=False,
        ),
    ]
