# Generated by Django 2.1.1 on 2019-10-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_stgeconomiczones_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stglocation',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Source Name'),
        ),
    ]
