# Generated by Django 2.1.1 on 2019-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20191002_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgeconomiczones',
            name='uuid',
            field=models.CharField(max_length=36, verbose_name='Universal ID'),
        ),
        migrations.AlterField(
            model_name='stglocation',
            name='public_access',
            field=models.CharField(default='false', max_length=6, verbose_name='Public Access'),
        ),
    ]
