# Generated by Django 2.1.1 on 2019-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20191005_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stglocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='maximum Value'),
        ),
        migrations.AddField(
            model_name='stglocation',
            name='logitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Target Value'),
        ),
    ]
