# Generated by Django 2.1.1 on 2019-10-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_auto_20191008_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stglocation',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
