# Generated by Django 2.1.1 on 2019-10-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20191008_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stglocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='stglocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
