# Generated by Django 2.1.1 on 2019-12-05 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactHealthCommodities',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('num_of_orders', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Orders')),
                ('order_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity Ordered')),
                ('issued_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity Issued')),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Date Issued')),
                ('comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('public_access', models.CharField(blank=True, default='true', max_length=6, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Commodities Order',
                'verbose_name_plural': 'Commodity Orders',
                'db_table': 'fact_health_commodities',
                'ordering': ('product__name', 'location__name'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgHealthCommodity',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('units_of_measure', models.CharField(blank=True, max_length=200, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('public_access', models.CharField(max_length=6)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Health Commodities',
                'db_table': 'stg_health_commodity',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facthealthcommodities',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodities.StgHealthCommodity', verbose_name='Product ID'),
        ),
    ]
