# Generated by Django 2.1.2 on 2020-09-30 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facthealthcommodities',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='stghealthcommodity',
            name='date_lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Modified'),
        ),
    ]
