# Generated by Django 2.1.1 on 2019-10-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20191002_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgresearchproposal',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='research.StgKnowledgePipeline', verbose_name='Pipeline Number'),
        ),
        migrations.AlterField(
            model_name='stgresearchpublication',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='research.StgKnowledgePipeline', verbose_name='Pipeline Number'),
        ),
    ]
