# Generated by Django 2.1.1 on 2019-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20191004_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgepipeline',
            options={'managed': True, 'ordering': ('title',), 'verbose_name': 'Knowledge Pipeline', 'verbose_name_plural': 'Knowledge Pipelines'},
        ),
        migrations.AlterField(
            model_name='stgresearchpublication',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Cover Page'),
        ),
        migrations.AlterField(
            model_name='stgresearchpublication',
            name='internal_link',
            field=models.FileField(blank=True, null=True, upload_to='media/files', verbose_name='File Link'),
        ),
    ]
