# Generated by Django 2.1.1 on 2019-10-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20191008_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgknowledgepipeline',
            name='domain',
        ),
    ]
