# Generated by Django 2.1.1 on 2019-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_stgknowledgepipeline_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgresearchthemes',
            name='domains',
            field=models.ManyToManyField(blank=True, db_table='link_disease_domain_members', to='research.StgDiseaseDomain', verbose_name='Disease Domains'),
        ),
    ]
