# Generated by Django 2.1.1 on 2019-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_stgresearchthemes_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgdiseasedomain',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Domain', 'verbose_name_plural': ' Research Domains'},
        ),
        migrations.AlterModelOptions(
            name='stgresearchthemes',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Theme', 'verbose_name_plural': 'Research Themes'},
        ),
        migrations.AddField(
            model_name='stgdiseasedomain',
            name='pipelines',
            field=models.ManyToManyField(blank=True, db_table='link_domain_pipelines', to='research.StgKnowledgePipeline', verbose_name='Knowledge Pipelines'),
        ),
        migrations.AlterField(
            model_name='stgdiseasedomain',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stgresearchthemes',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=230),
            preserve_default=False,
        ),
    ]
