# Generated by Django 2.1.2 on 2020-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataelement',
            name='end_year',
            field=models.IntegerField(default=2020, verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='start_year',
            field=models.IntegerField(default=2020, verbose_name='Start Year'),
        ),
    ]
