# Generated by Django 2.1.2 on 2020-10-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20201008_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdataelementgroup',
            name='dataelement',
            field=models.ManyToManyField(blank=True, db_table='link_data_element_members', to='elements.StgDataElement'),
        ),
    ]
