---

- hosts: prod
  user: khro
  name:  khro_app
  vars:
    khro_app_version: "0.0.1.dev0+rc10"
    load_default_data: true
    gunicorn_timeout: 60
    gunicorn_graceful_timeout: 1
    deploy_user: "deploy"
    deploy_group: "deploy"

  pre_tasks:
      - name: create deploy user
        user: name="{{deploy_user}}" groups=www-data,sudo state=present
        become: yes
  roles:
      # - common
      # - python
      # - postgresql
      - nginx
      - supervisor
      # - acct
      # - letsencrypt
      # - logrotate
      - {
          role: "letsencrypt_cert",
          certificate_domain: "khro.cislunar.co",
          tags: ["prod_api", "prod_api_cert"]
        }
      - {
          role: "khro_app",
          name: "khro_app",
          server_name: "khro.cislunar.co",
          allowed_hosts: ".cislunar.co, khro.cislunar.co",
          ssl_on: true,
          ssl_cert: "/etc/letsencrypt/live/khro.cislunar.co/fullchain.pem",
          ssl_cert_key: "/etc/letsencrypt/live/khro.cislunar.co/privkey.pem",
          ssl_trusted_certificate: "/etc/letsencrypt/live/khro.cislunar.co/chain.pem",
          tags: ["prod_api"]
        }
