# Generated by Django 2.1.1 on 2019-12-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StgEconomicZones',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('economiczone_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, verbose_name='Universal ID')),
                ('name', models.CharField(max_length=230, verbose_name='Economic Block')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Economic Block',
                'verbose_name_plural': 'Manage Economic Blocks',
                'db_table': 'stg_economic_zones',
                'ordering': ('code',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgLocation',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, verbose_name='Universal Key')),
                ('name', models.CharField(max_length=230, verbose_name='Location Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('code', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Location Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Longitude')),
                ('cordinates', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('end_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('source_system', models.CharField(blank=True, max_length=100, verbose_name='Source Name')),
                ('public_access', models.CharField(default='false', max_length=6, verbose_name='Public Access')),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': ' Organization Units',
                'db_table': 'stg_location',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgLocationLevel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('locationlevel_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('level 1', 'level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7')], default='level 1', max_length=50, verbose_name='Location Level')),
                ('name', models.CharField(max_length=230, verbose_name='Level Name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Organization Levels',
                'db_table': 'stg_location_level',
                'ordering': ('code',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stglocation',
            name='locationlevel',
            field=models.ForeignKey(help_text='You are not allowed to make changes to this Field ', on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocationLevel', verbose_name='Location Level'),
        ),
        migrations.AddField(
            model_name='stglocation',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, help_text='You are not allowed to edit this field', null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Parent Location'),
        ),
        migrations.AddField(
            model_name='stglocation',
            name='zone',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='regions.StgEconomicZones', verbose_name='Economic Block'),
        ),
    ]
