# Generated by Django 2.1.1 on 2020-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stglocation',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source Name'),
        ),
    ]
