# Generated by Django 2.1.1 on 2019-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdataelement',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stgdataelementgroup',
            name='dataelement',
            field=models.ManyToManyField(blank=True, db_table='stg_data_element_membership', to='elements.StgDataElement'),
        ),
    ]
