# Generated by Django 2.1.1 on 2019-10-05 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20191002_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgdataelementgroup',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Universal ID'),
        ),
    ]
