# Generated by Django 2.1.1 on 2019-10-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_stgdataelementgroup_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataelement',
            options={'managed': True, 'ordering': ('location',), 'permissions': (('approve_factdataelement', 'Can approve Data Element'), ('reject_factdataelement', 'Can reject Data Element'), ('pend_factdataelement', 'Can pend Data Element')), 'verbose_name': 'Data Element Value', 'verbose_name_plural': '  Data Form'},
        ),
    ]
